# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: George Arnall
title: George Arnall
email: george@garnall.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  # Our professional grade stainless steel cleaner and polish will give you 
  # a streak free shine in minutes. Perfect for domestic and professional use, 
  # try it today!

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://garnall.co.uk"
twitter_username: 
github_username:  georgearnall

# Build settings
markdown: kramdown
highlighter: rouge # or rouge or null
permalink: /:categories/:title/
navigation: 
  -    {name: "GitHub", url: "http://github.com/georgearnall"}
  -    {name: "Porfolio", url: "/porfolio/"}
  # -    {name: "Contact", url: "#"}
plugins:
  - jekyll-sitemap

# Where are tags and categories displayed
tag_page: '/tags/'
# category_page: '/blog/categories/'

sass:
  style: compact # possible values: nested expanded compact compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
